### ISSUE TITLE
Blank Table Using HoloLens

### ISSUE THREAD

**Issue by idogi124** [AR-Eye-Tracking-Toolkit/ARETT#4] opened 2021-09-22 10:21 UTC
Hi there, I’m using the ARETT toolkit with HoloLens 2, and the table comes out blank. What am I doing wrong?
Thanks!
![774E921E-E56F-4E16-A15F-D549D7953439](https://user-images.githubusercontent.com/91189536/134326834-d5f5ef98-d41b-4578-b874-6ec0ee9ad89b.jpeg)

**Comment by sekapp** [comment] 2021-09-22 11:45
Hi,

did you check and make sure that the HoloLens is being worn, the gaze permissions are given to the application and there exists a valid eye tracking calibration for the current wearer of the device?
When the HoloLens for example is just sitting on a table no data is being generated. I have also seen some cases where the HoloLens reports an existing and valid eye tracking calibration, however the calibration is actually missing also resulting in no data.
Maybe you can try wearing the device, calibrating the eye tracking, restarting the ARETT application and then start a new recording.

Best regards
Sebastian Kapp

**Comment by shogo1998** [comment] 2022-01-03 08:57
Hi ,
When I ran the demo on HoloLens2, the Control Interface showed "Calibration invalid" as shown in the figure, and I had the same problem as the person above. On the unity editor, it was "Calibration valid". I tried the comment above, but it doesn't work. What should I do?

![スクリーンショット (22)](https://user-images.githubusercontent.com/87409332/147913364-596f7c1c-57ce-4166-a6cc-bce8a01ab57d.png)

**Comment by sekapp** [comment] 2022-01-03 09:27
Hi,

did you run an eye-tracking calibration on the device before trying the demo and were you wearing it while accessing the control interface?
The device must be worn for data to be recorded and for the calibration to be valid. The calibration information provided in the control interface is directly taken from the device itself, i.e., there is no further logic or processing in the toolkit which might lead to an invalid calibration.
The "calibration valid" information in the editor is hardcoded as there is no eye-tracking calibration to check.

If you calibrated the device and still don't get data, can you check if you can use eye tracking for example in the [MRTK Example Application/Scene](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/example-scenes/eye-tracking-examples-overview?view=mrtkunity-2021-05)? If this also doesn't work the issue is with eye tracking on your device in general.

Sadly, if eye tracking works in other applications but not the ARETT Demo identifying the issue without access to your setup is difficult. What version of Unity/MRTK are you using and what Windows version are you running on the HL? Have you tried the versions for Unity and MRTK listed in the [Readme](https://github.com/AR-Eye-Tracking-Toolkit/ARETT#dependencies)? 
While compatibility with future versions of Unity and MRTK should be possible, I am unable to test all future version combinations.

Best regards
Sebastian Kapp

**Comment by wangsk-tum** [comment] 2022-03-10 18:03
> Hi , When I ran the demo on HoloLens2, the Control Interface showed "Calibration invalid" as shown in the figure, and I had the same problem as the person above. On the unity editor, it was "Calibration valid". I tried the comment above, but it doesn't work. What should I do?
> 
> ![スクリーンショット (22)](https://user-images.githubusercontent.com/87409332/147913364-596f7c1c-57ce-4166-a6cc-bce8a01ab57d.png)

Hi, shogo,

I got the same problem, the Calibration is "invalid" and no data was recorded in the csv file. 
Also, my application has the permission of the eye tracking in hololens, and the ET calibration from the Control Interface is correctly completed every time. I can also use eye tracking in the MRTK Example Applications.
I would like to know whether you found a way to fix this and get the gaze data correctly.

I appreciate your quick response.

Best,
wangsk

**Comment by wangsk-tum** [comment] 2022-03-15 16:16
Hi, I located the codes related to the issue and found a solution. 

In the file "DataAccessUWP", the program first caches the current spatial coordinate system (CSCS) using "WindowsMixedRealityUtilities.SpatialCoordinateSystem" in the function "UnityUpdate()". 

And then, in the function "CheckForEyeData", the program checks if CSCSis null. If CSCS is not null, the program can get gaze data by calling the function "SpatialPointerPose.TryGetAtTimestamp()" with CSCS as a parameter.

For my program (MRTK 2.7.3, Unity 2020.3.15f2), the CSCS is always null, that is why the gaze data is unavailable. I don't know why I can not get the correct CSCS by loading the default spatial coordinate system, perhaps it is my hololens's problem. Anyway, my solution is to create a spatial coordinate system instead of loading the default one.

Here are the changes in the code (file: "DataAccessUWP", function "UnityUpdate()"):
public void UnityUpdate()
{
#if (UNITY_WSA && DOTNETWINRT_PRESENT) || WINDOWS_UWP

//Original way to get the CSCS
//currentSpatialCoordinateSystem = WindowsMixedRealityUtilities.SpatialCoordinateSystem;

//Alternative way to get the CSCS
currentSpatialCoordinateSystem = SpatialLocator.GetDefault().CreateStationaryFrameOfReferenceAtCurrentLocation().CoordinateSystem;

#endif
}

I hope this solution can help those who have the same issue. Also, many thanks to Sebastian and your colleagues for making this toolkit.

Best,
wangsk

**Comment by sekapp** [comment] 2022-03-15 18:14
Hi wangsk,

thank you very much for your research and the fix! It seems to me that the issue is therefore most likely a change in the MRTK and Unity 2020, as I have developed and testet the scripts with previous versions. Looking at the MRTK source it most likely stems from changes with the XR system of Unity 2020, as the SpatialCoordinateSystem seems to be only used in older versions.
I will link your solution in the main readme.

For quick accesss, this should be a link to the file and line which needs the change: [/Scripts/DataAccessUWP.cs](../blob/master/Scripts/DataAccessUWP.cs#L274)

Maybe you can test the solution in your use case and if this fixes all issues and results in accurate data open a pull request.
Sadly I can't test the solution myself, which makes me hesitant to "blindly" add this change to the main repository. However, if the change has proven itself for you and ideally also for other users I'm happy to integrate it into the toolkit.

Best regards,
Sebastian Kapp

**Comment by serhangul** [comment] 2022-03-16 16:33
Hi. First of all: @sekapp Thank you Sebastian for the very useful library and excellent documentation!

I'm using Unity 2020.3.28f1 and MRTK 2.7.3. After getting a blank file with the unmodified version of ARETT, I tried the above suggestion from @wangsk-tum and I could get the gaze data without any issues. However, I have a problem with locating the objects hit by the gaze points. Although I have two gameobjects in my scene to which I alternatingly fixate, gazePointHit is almost always equal to False. The gameobjects (cubes) are assigned to the Default layer, as in the [demo scene ](https://github.com/AR-Eye-Tracking-Toolkit/ARETT-Demo). gazeOrigin and gazeDirection seem to be correct though, as far as I can tell.

To check, I tried the demo scene using Unity 2019.4. There I get correct values for gazePointHit and the gazePoint_target_{name,x,y,z,...}. So I think there should be some other changes between the Unity or MRTK version that causes a problem in raycasting. I will try to dig deeper and post here if I can fix the issue. Please share if you have some insights.

Thanks,
Serhan

**Comment by serhangul** [comment] 2022-03-16 18:26
I realized that the DefaultHololens2Configuration profile was set for the MixedRealityToolkit and spatial awareness was not enabled there. So, I created a custom profile and enabled spatial awareness. After that 3 different Spatial Observers were added.  

<img width="449" alt="spatial_obs" src="https://user-images.githubusercontent.com/4326033/158660853-11d939da-a25f-47a3-89bc-facf0300a97d.png">


Now, I can get some hits on the cubes but most of the hits are on the SpatialMesh, even while I'm fixating on the cubes; there are some occasional hits on the cubes though (please see the CSV below). Any ideas how to set this right?

[2022_03_16-18_51_05-serhan-rec1.csv](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/files/8267337/2022_03_16-18_51_05-serhan-rec1.csv)

**Comment by sekapp** [comment] 2022-03-16 21:08
Hi,

as said sadly I'm currently unable to do tests with Unity 2020 and the current MRTK myself. However, I'm happy to see the toolking being used and I will try to help as much as possible.

Did you check the gaze origin and direction in detail and also when moving around in the room? The gaze origin data in your csv only moves a few cm and stays very close to the global origin. The gaze origin should always be somewhere around the main camera position (which you can [easily log](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/wiki/Data-Provider#gameobjects-to-log)). As the raycasts are default Unity functions I would be surprised if there would be an issue there.

I currently would guess that the changes by wangsk might result in a different/offset spatial coordinate system being used when requesting gaze data compared to my original implementation. However, this is a blind guess with no further research on my side.
If you have both the 2020 version as well as 2019 running on a HL2, you could check and compare the gaze data between them (especially origin and rough direction compared to the main camera) and guess if the 2020 data seems plausible. As said, I would also reccomend moving around in the room to prevent "accidental matches" when the global origin is close to the camera and gaze origin.

Best regards
Sebastian Kapp

**Comment by serhangul** [comment] 2022-03-17 13:19
@sekapp Thanks for the feedback. I made further experiments moving around in the room and compared the gaze origin with the main camera position, as you suggested. With your original version, both values are almost equal. With the change from  @wangsk-tum they are significantly different. So I think you are right that the change results in a different spatial coordinate system. 

However, I did a bit of further research on the topic and came across [this ](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10082#issuecomment-905865993) answer in a Github issue for the MRTK project. This recommends using the `PerceptionInterop.GetSceneCoordinateSystem` method in the Unity OpenXR plugin package to get a spatial coordinate system. I gave it a try, and again compared the gaze origin and the camera position. In this case, the two values are almost equal and I do get hits on the cubes that I fixate. It seems that this one gives a correct spatial coordinate system!

To compare it yourself, you can check the CSV files that I've created for each version: the original Unity 2019, the suggestion from wangsk and the solution using the `PerceptionInterop` class. Note that for clarity, I only included the relevant columns such as gaze origin/direction, main camera position/rotation and the hit information.
[unity19.csv](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/files/8286228/unity19.csv)
[unity20_wangsk.csv](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/files/8286227/unity20_wangsk.csv)
[unity20_perception.csv](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/files/8286229/unity20_perception.csv)

I would be happy to create a branch for Unity 2020.3 and send a pull request but I need to do a bit more testing to verify that the above changes do not break any other functionality. I'm not sure if it is a good idea to mix OpenXR functions with the legacy MR Toolkit code, and perhaps some other parts need to be migrated to OpenXR as well. Any opinions/suggestions on that?

Btw a bit off-topic but do you have any idea, why gaze origin and main camera position are not exactly equal? I couldn't find any information on that.

**Comment by sekapp** [comment] 2022-03-17 17:32
Thank you for your research into this issue! It seems like my guess was correct and the apprach by wangsk is indeed a different coordinate system.

I would be happy to integrate a pull request into ARETT to add Unity 2020 compatibility if your tests succeed! Maybe you could add [directives](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) to use the current (old) method in Unity 2019 and your new fix when Unity 2020 (or newer) is used. It might even be possible to differentiate the XR plugins and use them as directives. This way I could simply update the main branch and keep compatibility with both Unity versions.
Apart from the SpatialCoordinateSystem I don’t think the code is using a lot of MRTK functions. The main other thing I could think of is the [conversion to Unity Vectors](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/blob/master/Scripts/DataAccessUWP.cs#L230). This is an extension from MRTK but should not change with updates. Other than that, a few functions to check permissions are used, however if those would be broken it should be immediately obvious. In general, all MRTK functions should be limited to the DataAccessUWP class so you can simply check there.


Regarding the origin differences: I can think of two reasons.
The first reason could simply be, that the gaze origin is different from the unity camera origin. As the whole scene is e.g., rendered differently for both eyes it could be that the camera origin is a "theoretical"/"center" origin and does not match the origin of the real eye gaze.
Other than that, the differences in data rate and time at which the positions are recorded also plays a role. As ARETT collects the gaze data asynchronously from the framerate, the origin might simply be at a different point at the different times. Looking at your csv recordings, it seems like the gaze origin could be lagging behind the camera origin by few lines. This could also be the overhead/delay of eye image capturing and processing by the device. This is also the reason why I tried to decouple the gaze processing and the framerate as much as possible and to focus on the raw gaze API and data to deduct the gaze point. However, the main ray cast sadly still has to happen during the main Unity frame updates due to Unity limitations.

**Comment by serhangul** [comment] 2022-03-22 11:30
Thanks for sharing your insights and pointer to the directives / conditional compilation. That seems to be the best option to maintain compatibility with different Unity versions while using the main branch.

Gaze data being collected asynchronously from the frame rate sounds like a reasonable explanation to me for the difference from the head pose. I considered verifying the head pose by checking the property [SpatialPointerPose.Head ](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.spatial.spatialpointerpose.head?view=winrt-22000#windows-ui-input-spatial-spatialpointerpose-head) returns the user's head gaze for a given timestamp but I guess the position of the main camera logged by ARETT returns the same information.

I collected some more data and checked the output, esp. if the gaze target names and AOIs are correct. I couldn't detect any problems with eye gaze data so far with Unity 2020.3 after the above fix for SpatialCoordinateSystem. The only issue I've detected is with the accuracy grid. In apps built with Unity 2020.3, the top row of the grid is not visible, so I see 6 dots in total. The reason is not clear to me because all settings are equal between the 2019.4 and 2020.3 projects. Also in Unity 2020.3, all 9 dots seem to be in the viewport of the WebcamCamera. However, when deployed to HL2, 2020.3 version doesn't show the top row for any of the distances 0.5m to 4m. Any ideas here?

**Edit:** The accuracy grid seems to be shifted upwards in HL2 display using 2020.3, that's why the top row does not fit into the field of view. This is strange because the position and FoV of the camera, and the position of AccuracyGrid are exactly the same in both Unity projects.

**Comment by sekapp** [comment] 2022-03-22 16:24
As I haven't used Unity 2020 myself I sadly don't have any ideas where this shift comes from. Maybe for your use case you can try shifting the grid so it matches the FoV again.

**Comment by serhangul** [comment] 2022-03-24 15:49
> Regarding the origin differences: I can think of two reasons. The first reason could simply be, that the gaze origin is different from the unity camera origin. As the whole scene is e.g., rendered differently for both eyes it could be that the camera origin is a "theoretical"/"center" origin and does not match the origin of the real eye gaze. Other than that, the differences in data rate and time at which the positions are recorded also plays a role. As ARETT collects the gaze data asynchronously from the framerate, the origin might simply be at a different point at the different times. Looking at your csv recordings, it seems like the gaze origin could be lagging behind the camera origin by few lines. This could also be the overhead/delay of eye image capturing and processing by the device. This is also the reason why I tried to decouple the gaze processing and the framerate as much as possible and to focus on the raw gaze API and data to deduct the gaze point. However, the main ray cast sadly still has to happen during the main Unity frame updates due to Unity limitations.

Just to follow up on this: In the legacy Mixed Reality documentation for WinRT APIs given [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/gaze-in-directx), there is some interesting explanation:
_**Head-gaze** represents the direction that the user's head is pointed in. Think of head-gaze as the position and forward direction of the device itself, with the **position as the center point between the two displays**. Head-gaze is available on all Mixed Reality devices.
**Eye-gaze** represents the direction that the user's eyes are looking towards. **The origin is located between the user's eyes.** It's available on Mixed Reality devices that include an eye tracking system._

I think this clarifies difference between the head position and eye gaze origin. Of course, synchronization issues caused by image processing delays or asynchronous processing (as pointed out by @sekapp) might be another factor.

**Comment by sekapp** [comment] 2023-05-26 14:51
With the [update to Unity 2021](https://github.com/AR-Eye-Tracking-Toolkit/ARETT/releases/tag/v2.0.0) this issue should be resolved.

**Closed as completed by sekapp** 2023-05-26 14:51 UTC
